export const siteConfig = {
  name: "Jaime Syvino",
  pronouns: "she/her",
  tagline: "Experienced Engineering Leader",
  subLine: "Velocity and vibes — I own both, and I don't think you get one without the other",
  location: "New Paltz, NY (Remote)",
  email: "JSyvino@gmail.com",
  summary: {
    blurb:
      "I'm an engineering leader who has spent the last several years building and scaling product engineering teams, most recently across AI-native edtech, sustainability data, and enterprise SaaS.",
  },
  links: {
    linkedin: "https://www.linkedin.com/in/jaime-syvino-engineer/",
    github: "https://github.com/jsyvino",
    resume: "/resume/Jaime-Syvino-Resume.pdf",
  },
  nav: [
    { label: "About", href: "/about" },
  ],
  careerStats: [
    { value: "8+", label: "years shipping software" },
    { value: "9", label: "engineers led at once", sublabel: "at peak" },
    { value: "3", label: "companies, one throughline", sublabel: "ship, measure, lead" },
  ],
  skills: {
    technical: [
      "React",
      "Next.js",
      "TypeScript",
      "Redux",
      "Zustand",
      "Node.js",
      "Express",
      "LLM Integration",
      "Python / Django",
      "PostgreSQL",
      "Supabase",
      "BigQuery",
      "ElasticSearch",
      "AWS",
      "A/B Testing",
      "Datadog",
      "Sentry",
      "Amplitude",
      "Braintrust",
      "Vercel",
      "Storybook",
      "Material UI",
      "Playwright",
      "Cypress",
      "Project Management",
    ],
    leadership: [
      "Hiring",
      "Servant Leadership",
      "Cross-functional Alignment",
      "Mentorship",
      "Building Psychological Safety",
      "Decisive Ownership",
      "Feedback Culture",
      "Team Accountability",
      "Sustainable Performance",
      "Strategic Tradeoffs",
      "Stakeholder Management",
      "Clear Communication",
      "Conflict Resolution",
      "Risk Management",
      "Priority Setting",
      "Execution Excellence",
      "Talent Development",
      "Empowering Others",
      "Shared Accountability",
      "Healthy Boundaries",
      "Outcome Orientation",
      "Organizational Clarity",
      "Change Leadership",
      "Coaching",
      "Consensus Building",
      "Resilient Leadership",
      "Culture Building",
      "Difficult Decisions",
      "Customer Focus",
      "Operational Discipline",
    ],
  },
};
